#!/usr/bin/env bash

dual_monitor() {
    bspc monitor primary -n Main -d 1 2 3
    bspc monitor ^1 -n Second -d 4 5 6 7 8 9 10
}

# Monitor setup
bspc control --reset-desktops

if [[ $(xrandr -q | grep -w DP-1-0) =~ \ connected ]]; then
    echo "Setting up HOME mode..."
    ~/.screenlayout/HOME.sh
    dual_monitor

elif [[ $(xrandr -q | grep -w HDMI-1-0) =~ \ connected ]]; then
    echo "Setting up WORK mode..."
    ~/.screenlayout/WORK.sh
    dual_monitor

else
    echo "Setting up SINGLE mode..."
    ~/.screenlayout/SINGLE.sh
    bspc monitor primary -n Main -d 1 2 3 4 5 6 7 8 9 10
fi

# BSPWM Specific

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config focused_border_color "$(xrdb -get color14)"
bspc config normal_border_color "$(xrdb -get background)"
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# XORG

xsetroot -cursor_name left_ptr

# One-shots

bspc rule -a firefox        desktop=2 --one-shot
bspc rule -a Zotero         desktop=3 --one-shot # because pop-ups
bspc rule -a Google-chrome  desktop=5 --one-shot
bspc rule -a telegram       desktop=5 --one-shot

# Consistent

bspc rule -a notion-app     desktop=1
bspc rule -a Todoist        desktop=1
bspc rule -a Code           desktop=3
bspc rule -a jetbrains-idea desktop=3
bspc rule -a Spotify        desktop=4
bspc rule -a discord        desktop=5
bspc rule -a Mattermost     desktop=5
bspc rule -a Slack          desktop=5
bspc rule -a Postman        desktop=7
bspc rule -a Steam          desktop=8

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a origin.exe state=floating

# Background applications

"$HOME"/.config/polybar/launch_hidden.sh --forest 3 &
feh --bg-fill ~/Pictures/wallpaper.jpg &
dunst -config "$HOME"/.config/dunst/dunstrc &
picom -r 2 -o .7 -l 5 -t 5 -D 2 --shadow-exclude "class_g = 'Firefox' && argb" &

# Startup applications
startups
~/.scripts/hellowikipedia.sh
