#!/bin/bash

function startnotrunning() {
	if [ "$(pgrep -c "$1")"  -ge 1 ]; then
		echo "Not running $1"
	else
		echo "Running new instance of $1"
		"$@" & disown
	fi
}

startnotrunning kitty btop
startnotrunning firefox
startnotrunning todoist
startnotrunning webwhatsapp
startnotrunning telegram-desktop
startnotrunning redshift -l 52.011578:4.357068
